### ISSUE TITLE
Load glb file 

### ISSUE THREAD

**Issue by Ikamyshev** [fire/godot#5]
**Godot version: 3.2.4.rc.custom_buid**

**OS/device including version:Ubuntu 20.04**

**Issue description: I am trying to load a glb file but I get an error **

**Steps to reproduce:
func _ready():
	var s = EditorSceneImporterGLTF.new()
	var importer = EditorSceneImporterGLTF.new()
	var node = importer.import_gltf("user://Meshes/UFO_Empty.glb", 1, 1)

Error: Invalid call. Nonexistent function 'import_gltf' in base 'Nill'.

**

**Minimal reproduction project:**

**Comment by Ikamyshev** [comment]
Just now noticed a console message:
ERROR: instance: Class 'EditorSceneImporterGLTF' can only be instantiated by editor.
   At: core/class_db.cpp:555.
ERROR: _new: Class type: 'EditorSceneImporterGLTF' is not instantiable.
   At: modules/gdscript/gdscript.cpp:70.
Do I understand correctly that it is impossible to load an file in real-time?

**Comment by fire** [comment]
I wanted to make this for Godot 4 but my feature proposal for a runtime gltf importer was denied.

**Comment by Ikamyshev** [comment]
This is a pity.
I am making an application where each user has his own visual environment.
Could you give some recommendations so that I could try to do it myself?

**Comment by fire** [comment]
The editor import mesh class is easily removable, make it a mesh instance and it should be possible to run the module at game time. Alternatively use tools=yes and ship the editor.

**Comment by Ikamyshev** [comment]
Thank you very much, it worked.
You are doing a great job!
